### ISSUE TITLE
Using With Netbeans

### ISSUE THREAD

**Issue by jedielson** [bitnami/bitnami-docker-wildfly#27]
Hi.

When we persist files at host, we have this structure

|- path/to/my/wildfly
   |- bin
   |- conf
   |- data

But I want to use my wildfly server wo support my development with Netbeans.

The Netbeans plugin to wildfly look for this structure
- path/to/my/wildfly
  --> standalone
  ---> configuration
  ----> standalone.xml 

How can we solve it?

**Comment by sameersbn** [comment]
The `standalone.xml` configuration is saved in the `conf/` directory of the host mounted volume. Please check if netbeans can be configured to use this path.

The image was designed to be used for application deployment and may not work if netbeans expects the path `.../standalone/configuration/standalone.xml`. We are definitely considering adding support for development using this image.

**Comment by sameersbn** [comment]
Hello again,

I've been testing the requirements of your use-case and while it's not officially supported by the Bitnami image right now, you can use these "**unofficial and unsupported**" instructions (a.k.a workaround) to get the setup working for you:

#### Start the Wildfly image with a host volume (the normal stuff)

```bash
$ mkdir ~/wildfly-dev
$ cd ~/wildfly-dev
$ docker run --name wildfly -itd --volume ~/wildfly-dev:/bitnami/wildfly -p 8080:8080 -p 9990:9990 bitnami/wildfly
```

#### The hack

It appears the wildfly netbeans plugin requires access to a few components from the wildfly installation directory, namely:

 - standalone/
 - modules/
 - jboss-modules.jar 

The contents of the standalone directory are already present in the host volume, so we only need to setup symbolic links:

```bash
$ mkdir standalone
$ ln -sf ../conf standalone/configuration
$ ln -sf ../data standalone/domains
```

The final part is to copy the `modules/` directory and the `jboss-modules.jar` file to the host volume, which you may have to repeat when you update the wildfly image version:

```bash
$ docker cp wildfly:/opt/bitnami/wildfly/modules .
$ docker cp wildfly:/opt/bitnami/wildfly/jboss-modules.jar .
```

The directory hierarchy of the wildfly host volume should look something like this:

```bash
$ tree -L 2
.
├── bin
│   └── standalone.conf
├── conf
│   ├── application-roles.properties
│   ├── application-users.properties
│   ├── logging.properties
│   ├── mgmt-groups.properties
│   ├── mgmt-users.properties
│   ├── standalone-full-ha.xml
│   ├── standalone-full.xml
│   ├── standalone-ha.xml
│   ├── standalone.xml
│   └── standalone_xml_history
├── data
│   └── README.txt
├── jboss-modules.jar
├── modules
│   └── system
└── standalone
    ├── configuration -> ../conf
    └── domains -> ../data
``` 

Now you should be able to configure netbeans as required.

**Comment by jedielson** [comment]
Thanks for your response.

I'm trying do it but I'm using docker for windows.

I'll try it into a linux machine ASAP.

Is it possible turn this feature officially suported?

One more time, thanks for your support!!!!

**Comment by sameersbn** [comment]
> Is it possible turn this feature officially suported?

The trouble is with copying modules/ and jboss-modules.jar to the data volume by default. 

We are considering offering a development version of the image (or add env vars to indicate development with netbeans), but I cannot commit to a time frame in which this could be made available.

**Comment by jedielson** [comment]
Ok.

One more time, thanks for your support.
I'll wait for the news.

0/
