### ISSUE TITLE
Stopping the container doesn't clean shutdown the wildfly server

### ISSUE THREAD

**Issue by myannou** [bitnami/bitnami-docker-wildfly#59]
With the bitnami/wildfly:12.0.0 image the wildfly server starts correctly
but when I try to either do a docker stop or a CTRL + C the wildfly server is stopped immediately without a "clean shutdown": it is killed.
its seems the SIGNAL is not send to the child's process group.
I tried to play with the tini command adding the "-g" option but without success 

Do you have an idea on how to trigger a "clean shutdown" for wildfly when stopping the container ?

Thank
Yann

**Comment by andresbono** [comment]
Hi @myannou, could you try the following?

- Modify the [rootfs/app-entrypoint.sh](https://github.com/bitnami/bitnami-docker-wildfly/blob/master/12/rootfs/app-entrypoint.sh) file as follows:

```diff
...
-exec tini -- "$@"
+exec tini -- /opt/bitnami/wildfly/bin/standalone.sh -Dwildfly.as.deployment.ondemand=false
```

- Rebuild the container. You can use a different tag:

```
docker build -t bitnami/wildfly:dev .
```

- Then run the container:

```
docker run -it bitnami/wildfly:dev
```
If you send a signal to the process it will be handled by wildfly. Does it work for you?

-Andrés B.

**Comment by myannou** [comment]
Hi,
I modify app-entrypoint.sh as you suggested.
And now either "CTRL + C" or "docker stop" works as expected : Wildfly server clean shutdown correctly .
we can see in the logs:
*** JBossAS process (117) received TERM signal ***

the only issue is we cannot start easily a bash command with this image: 
as "app-entrypoint.sh"is a docker ENTRYPOINT then 
`docker run -it bitnami/wildfly:dev bash`
will not launch a bash command in the container but launch the wildfly process
of course we can overwrite the entrypoint:
`docker run -it --entrypoint "" bitnami/wildfly:dev bash`
but it is not convenient..

Thanks
Yann

**Comment by myannou** [comment]
to avoid the issue with the entrypoint I changed the script "app-entrypoint.sh" as follow:
`#!/bin/bash -e

. /opt/bitnami/base/functions
. /opt/bitnami/base/helpers

print_welcome_page

if [[ "$1" == "nami" && "$2" == "start" ]] || [[ "$1" == "/init.sh" ]]; then
  nami_initialize wildfly
  info "Starting wildfly... "
  exec tini -- /opt/bitnami/wildfly/bin/standalone.sh -Dwildfly.as.deployment.ondemand=false
else
  exec tini -- "$@"
fi`

**Comment by andresbono** [comment]
Hi @myannou,

That's actually a much better way to do it!

-Andrés B.
