### ISSUE TITLE
enabling Oracle ecommerce ATG integration points with Jboss-EAP-6.4 & on premise Oracle DB

### ISSUE THREAD

**Issue by kavicse87** [bitnami/bitnami-docker-wildfly#65]
Can you please direct us with the below items that we wanted to do as part of the app integration.. We’re doing all this to migrate the oracle ecommerce ATG from on perm to kubernetes . Your help and advise on this would be much helpful to move forward.

1. We’ve deployed the jboss-eap-6.4 on domain mode in the k8s cluster which is running on azure. It has a domain controller and 5 host controllers and we used HA profile.
   2. We need to connect jboss app with on-premise oracle db. With this we need to integrate other ATG components as well. Is there any standard or best practise to enable the integration ?

**Comment by rafariossaa** [comment]
Hi, @kavicse87 
   I'll try to give you some help, but take into account that don't run this kind of applications on that kind of environment, so take this with a pinch of salt. 

  If I understood you well, you have an application running on a azure k8s cluster but you have to connect it to a on premise oracle DB, isn't it ?

  It is not very clear to me if your question is about how to integrate with other ATG components or how to connect a azure k8s application to a on premise database.

  For the second case, you will need to expose you database to internet, and you will have the problem of that the origin of the connection can change. To make a secure environment I would use a VPN between the k8s and the on-premise database, and put a lot of controls to make sure the origin of the connection is the desired one.

  For the first case, that depends on how those components interact with each other. I think oracle can give better suggestions.

 In any case, I'd suggest you to open an issue to oracle to ask for this kind of advise, they know better their products and which architectures or best practices suit best in these cases.
