### ISSUE TITLE
CVE scans for wildfly runtime

### ISSUE THREAD

**Issue by jkleinlercher** [bitnami/bitnami-docker-wildfly#69]
**Description**

It seems that the CVE scan reports only show CVEs of the OS modules, but not of the Wildfly Runtime itself. Do you just scan the os image and not the wildfly runtime on top?

for example the report for tag 19-debian-10 shows only one cve in glibc, but none in wildfly:

https://quay.io/repository/bitnami/wildfly/manifest/sha256:b701f836e7b11541391b7928e0d67917205a7379c82c9b2aba7a0d89967f06b2?tab=vulnerabilities

however, there where critical CVEs in Wildfly 19.0 for sure.

**Comment by andresbono** [comment]
Hi @jkleinlercher, as far as I know, quay.io only reports issues with the system packages and that is something that cannot be reconfigured for us as container publishers.

There are other CVE scanners like Trivy that also look for package files like `package.json` or `Gemfile.lock`. You can see the difference between the reports of an old image and the latest one:

```console
$ docker run --rm -it aquasec/trivy i --severity HIGH,CRITICAL bitnami/wildfly:19-debian-10
$ docker run --rm -it aquasec/trivy i --severity HIGH,CRITICAL bitnami/wildfly:latest
```

We would recommend you to use the latest version of the containers for the branches that we support, those will be receiving regular updates for all the components bundled in the container images: https://github.com/bitnami/bitnami-docker-wildfly#user-content-supported-tags-and-respective-dockerfile-links
