### ISSUE TITLE
Support `arm64`

### ISSUE THREAD

**Issue by t1** [bitnami/bitnami-docker-wildfly#76]
For all Raspberry Pie ARM and MacBook Pro M1/Pro/Max users, it would be very nice to have these images not only for `linux/amd64`, but also for `linux/arm64`. I didn't immediately see how these images are being built, but creating multi-architecture builds boils down to executing `docker buildx build --push --platform linux/arm64,linux/amd64 .`. More details are [here](https://docs.docker.com/desktop/multi-arch/).

**Comment by carrodher** [comment]
Hi, we just created this issue https://github.com/bitnami/charts/issues/7305 that is pinned in the Bitnami Helm Charts repository, on this way we can funnel all the conversation in a single place regarding ARM64 support.

We will close the rest of the existing issues just to avoid duplications, please visit the above-mentioned issue to see any new (when possible) about this topic.
