### ISSUE TITLE
java 17 based image

### ISSUE THREAD

**Issue by ssill2** [bitnami/bitnami-docker-wildfly#79]
### Name and Version

bitnami/wildfly:26

### What is the problem this feature will solve?

Since the EOL of java11 is roughly 2 years away,   Folks will need to start making required changes to their applications and work with java17.   I currently use this image as-is for the java11 version of my JEE applications.  I just went through the painful process to port my app from 11-17 and i was going to test deploying it via minikube.  I can't seem to find a java17 version of the bitnami/wildfly image. 

### What is the feature you are proposing to solve the problem?

Supply a tag of the bitnami/wildfly image that uses openjdk 17 instead of 11.

### What alternatives have you considered?

As I'm just getting into this I've not had a chance to consider alternatives.  I actually assumed there was already a tag I could use that used openjdk17.  Given there's some time before it really becomes critical to upgrade to java 17 I could investigate building my own image if needed.   I found your image to be just the ticket though for providing a secured wildfly image that I could deploy my apps on.

**Comment by javsalgar** [comment]
Hi,

Thank you so much for the feedback! I'm afraid that currently our automated system does not support having multiple java-based flavours. I will share this feedback to the team but I'm afraid you may need to create a forked version of the container changing the java version provided in the `unpack` instruction.


https://github.com/bitnami/bitnami-docker-wildfly/blob/master/26/debian-10/Dockerfile

```
RUN . /opt/bitnami/scripts/libcomponent.sh && component_unpack "java" "11.0.14-7" --checksum 900545c4f346a0ece8abf2caf64fd9d4ab7514967d4614d716bf7362b24f828b

```

You can change it to this:

```
RUN . /opt/bitnami/scripts/libcomponent.sh && component_unpack "java" "17.0.2-10" --checksum 70dbc5d64a8ae02f4898685ccaf993e0469ad804c87961e1e3b1a41046292a39

```

Source: https://github.com/bitnami/bitnami-docker-java/blob/master/17/debian-10/Dockerfile

**Comment by ssill2** [comment]
oh cool, I was looking at that in case you guys weren't ready.    I definitely think you guys should consider it though,  openjdk 11 EOLs in 2024 and openjdk8 EOLs in 2026.   There will be a lot of people that put this migration off and then realize how much of a pain it is.   In the meantime I'll definitely look at doing a local fork to test with.
Thanks for the info!

**Comment by ssill2** [comment]
just wanted to let you guys know the instructions you guys gave worked perfectly!  I got my app up and running with a locally built copy of your image with the changes you specified.
Thanks!

**Comment by ssill2** [comment]
Should I reopen this so it can be tracked as a to-do?

**Comment by javsalgar** [comment]
I will re-open it and mark it as on-hold

**Comment by ssill2** [comment]
sounds good!  thanks!

**Comment by ssill2** [comment]
hey just checking in.  I've been maintaining a java17 branch of my stuff in anticipation of of being able to switch.  I was wondering if you could give me an updated version of the java 17 work-around from above, but with updated version and hash.  Or if you could tell me how to get it, that's be fine too.  Thanks!

**Comment by javsalgar** [comment]
Hi!

You can find the hashes in the github.com/bitnami/bitnami-docker-java repository. Open the proper folder and look for the Dockerfile.

**Comment by ssill2** [comment]
thanks!

**Comment by ssill2** [comment]
that worked great thank you.

**Comment by ssill2** [comment]
you guys have an auto-built jdk17 image now?
